/**
 * Regenerates src/core/tokens/generated.ts from the Fluent web themes.
 *
 *   npm run tokens
 *
 * The token list is snapshotted into the package so that consumers do not need
 * Fluent installed to run a scan or a plan.
 */
import { createRequire } from 'node:module';
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { formatHex, formatHex8, parse as parseColor } from 'culori';
import type { FluentToken, TokenFamily, TokenRole, TokenState } from '../src/core/tokens/types.js';

const require = createRequire(import.meta.url);
const { webLightTheme, webDarkTheme } = require('@fluentui/react-theme');
const { version } = require('@fluentui/react-theme/package.json');

const OUTPUT = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  '../src/core/tokens/generated.ts',
);

function normalize(value: unknown, token: string): string {
  const parsed = parseColor(String(value));
  if (!parsed) throw new Error(`Cannot parse value "${String(value)}" of token ${token}`);
  const alpha = parsed.alpha ?? 1;
  return alpha < 1 ? formatHex8(parsed) : formatHex(parsed);
}

function roleOf(body: string): TokenRole {
  if (body.includes('Foreground')) return 'foreground';
  if (body.includes('Shadow')) return 'shadow';
  if (body.includes('Stroke') || body.includes('Border')) return 'stroke';
  if (body.includes('Background')) return 'background';
  return 'other';
}

function familyOf(body: string): TokenFamily {
  if (body.includes('Stencil')) return 'stencil';
  if (body.startsWith('Palette')) return 'palette';
  if (body.startsWith('Status')) return 'status';
  if (body.startsWith('Neutral')) return 'neutral';
  if (body.startsWith('Compound')) return 'compound';
  if (body.startsWith('Brand')) return 'brand';
  if (body.startsWith('Subtle')) return 'subtle';
  if (body.startsWith('Transparent')) return 'transparent';
  return 'other';
}

function stateOf(body: string): TokenState {
  if (body.endsWith('Hover')) return 'hover';
  if (body.endsWith('Pressed')) return 'pressed';
  if (body.endsWith('Active')) return 'active';
  if (body.endsWith('Selected')) return 'selected';
  if (body.includes('Disabled')) return 'disabled';
  if (body.includes('Focus')) return 'focus';
  return 'rest';
}

function variantOf(body: string, family: TokenFamily): string | undefined {
  if (family !== 'palette' && family !== 'status') return undefined;
  const withoutFamily = body.replace(/^(Palette|Status)/, '');
  const variant = withoutFamily.replace(/(Foreground|Background|Border|Stroke).*$/, '');
  return variant || undefined;
}

function describe(name: string, light: string, dark: string): FluentToken {
  const body = name.replace(/^color/, '');
  const family = familyOf(body);
  const variant = variantOf(body, family);
  return {
    name,
    role: roleOf(body),
    family,
    state: stateOf(body),
    rank: Number.parseInt(/\d+/.exec(body)?.[0] ?? '0', 10),
    ...(variant ? { variant } : {}),
    ...(body.includes('Inverted') ? { inverted: true } : {}),
    ...(light === dark ? { fixed: true } : {}),
    ...(body.includes('OnBrand') ? { onBrand: true } : {}),
    ...(body.includes('Link') ? { link: true } : {}),
    light,
    dark,
  };
}

const tokens: FluentToken[] = Object.keys(webLightTheme)
  .filter((name) => name.startsWith('color'))
  .sort()
  .map((name) =>
    describe(name, normalize(webLightTheme[name], name), normalize(webDarkTheme[name], name)),
  );

const body = tokens
  .map((token) => `  ${JSON.stringify(token)},`)
  .join('\n')
  .replaceAll('"', "'")
  .replace(/'(\w+)':/g, '$1:');

const file = `// Generated by scripts/generate-tokens.mts from @fluentui/react-theme@${version}.
// Run \`npm run tokens\` to refresh. Do not edit by hand.
import type { FluentToken } from './types.js';

export const FLUENT_THEME_VERSION = '${version}';

export const FLUENT_TOKENS: readonly FluentToken[] = [
${body}
];
`;

await writeFile(OUTPUT, file, 'utf8');
console.log(`Wrote ${tokens.length} tokens from @fluentui/react-theme@${version}`);
